fragment userBestRepoInfo on User {
	...userInfo
	repositories(
		orderBy: { field: STARGAZERS, direction: DESC }
		first: 1
		isFork: false
		ownerAffiliations: OWNER
	) {
		nodes {
			id
			name
			description

			...languagesInfo

			...starInfo
		}
	}
}
