onlyBuiltDependencies:
 - esbuild

patchedDependencies:
 '@sveltejs/package': patches/@sveltejs__package.patch

packages:
 - 'packages/*'
 - 'docs'

catalogs:
 tooling:
  '@typescript/native-preview': 7.0.0-dev.20260112.1
  esrap: https://pkg.pr.new/sveltejs/esrap@87
  oxc-parser: 0.108.0
  oxc-walker: 0.6.0
  'typescript': '5.9.2'
  'esbuild': '0.27.0'
  'commander': '14.0.0'
  'ora': '9.0.0'
  'tsx': '4.21.0'
  picospinner: 3.0.0

 vite:
  'vite': '^7.0.0'

 testing:
  # unit
  'vitest': '4.0.13'
  '@vitest/ui': 4.0.13
  '@vitest/coverage-v8': '4.0.13'
  '@vitest/browser-playwright': '4.0.13'
  vitest-browser-svelte: 2.0.1
  # e2e
  '@playwright/test': '1.57.0'

 linting:
  '@e18e/eslint-plugin': ^0.1.1
  '@eslint/compat': '1.4.0'
  '@eslint/js': '9.39.1'
  '@types/eslint': '9.6.1'
  '@typescript-eslint/parser': '8.53.0'
  'eslint': '9.39.1'
  'eslint-config-prettier': '10.1.5'
  'eslint-plugin-pnpm': '1.4.3'
  'eslint-plugin-svelte': '3.14.0'
  'globals': '17.0.0'
  'typescript-eslint': '8.53.0'
  jsonc-eslint-parser: 2.4.0
  yaml-eslint-parser: 1.3.0

 formatting:
  'prettier': '^3.6.1'
  '@ianvs/prettier-plugin-sort-imports': '^4.7.0'
  'prettier-plugin-sh': '^0.18.0'
  'prettier-plugin-svelte': '^3.4.0'
  'prettier-plugin-tailwindcss': '^0.7.0'

 linting-oxc:
  oxlint: 1.39.0
  oxlint-tsgolint: 0.11.0
  eslint-plugin-oxlint: 1.39.0

 lib-author-helper:
  '@changesets/changelog-github': '0.5.1'
  '@changesets/cli': '2.29.7'
  'publint': '0.3.1'
  'tslib': '2.8.0'
  'rollup-plugin-visualizer': '6.0.1'

 lib-dep-publish:
  'esm-env': '^1.2.2'
  '@types/vary': '1.1.3'
  'vary': '^1.1.2'
  '@types/micromatch': '4.0.9'
  'micromatch': '4.0.8'

 sveltekit:
  '@sveltejs/kit': '2.49.0'
  '@sveltejs/package': '2.5.4'
  '@sveltejs/vite-plugin-svelte': '6.2.1'
  '@sveltejs/adapter-auto': '7.0.0'
  '@sveltejs/adapter-node': '5.5.0'

 svelte:
  'svelte': '5.46.0'
  'svelte-check': '4.3.0'

 svelte-dep:
  '@sveltejs/kit': '^2.16.0'
  'svelte': '^5.0.0'

 remult:
  'remult': '3.3.4'

 docs:
  '@astrojs/starlight': 0.37.1
  accessible-astro-components: 5.1.1
  astro: 5.16.0
  astro-icon: 1.1.5
  sharp: 0.34.1
  prettier-plugin-astro: 0.14.1
