onlyBuiltDependencies:
 - esbuild

patchedDependencies:
 '@sveltejs/package': patches/@sveltejs__package.patch

packages:
 - 'packages/*'
 - 'docs'

catalogs:
 tooling:
  'typescript': '5.8.2'
  'esbuild': '0.25.0'
  '@babel/parser': 7.27.0
  '@babel/types': 7.27.0
  'rimraf': '6.0.1'
  'commander': '14.0.0'
  'ora': '8.2.0'
  'recast': '^0.23.4'
  'tsx': '4.20.3'

 vite:
  'vite': '^6.3.5'

 testing:
  # unit
  'vitest': '3.2.0'
  '@vitest/ui': 3.2.0
  '@vitest/coverage-v8': '3.2.0'
  '@testing-library/jest-dom': '6.6.3'
  '@testing-library/svelte': '5.2.4'
  'jsdom': '26.1.0'
  # e2e
  '@playwright/test': '1.53.1'

 linting:
  '@eslint/compat': '1.3.1'
  '@eslint/js': '9.29.0'
  '@theguild/prettier-config': '3.0.0'
  '@types/eslint': '9.6.1'
  '@typescript-eslint/parser': '8.35.0'
  'eslint': '9.29.0'
  'eslint-plugin-pnpm': '0.3.1'
  'eslint-plugin-svelte': '3.10.0'
  'eslint-plugin-unused-imports': '4.1.4'
  'globals': '16.2.0'
  'prettier': '^3.5.3'
  'prettier-plugin-svelte': '3.4.0'
  'prettier-plugin-tailwindcss': '0.6.6'
  'typescript-eslint': '8.35.0'
  jsonc-eslint-parser: 2.4.0
  yaml-eslint-parser: 1.3.0

 lib-author-helper:
  '@changesets/changelog-github': '0.5.1'
  '@changesets/cli': '2.29.1'
  'publint': '0.3.1'
  'tslib': '2.8.0'
  'rollup-plugin-visualizer': '6.0.1'

 lib-dep-publish:
  'esm-env': '^1.2.2'
  '@types/vary': '1.1.3'
  'vary': '^1.1.2'
  '@types/micromatch': '4.0.9'
  'micromatch': '4.0.8'

 sveltekit:
  '@sveltejs/kit': '2.22.2'
  '@sveltejs/package': '2.3.7'
  '@sveltejs/vite-plugin-svelte': '5.1.0'
  '@sveltejs/adapter-auto': '6.0.0'
  '@sveltejs/adapter-node': '5.2.12'

 svelte:
  'svelte': '5.34.8'
  'svelte-check': '4.2.1'

 svelte-dep:
  '@sveltejs/kit': '^2.16.0'
  'svelte': '^5.0.0'

 remult:
  'remult': '3.0.5'

 docs:
  '@astrojs/starlight': 0.34.1
  accessible-astro-components: 4.1.0
  astro: 5.10.1
  astro-icon: 1.1.5
  sharp: 0.34.1
  prettier-plugin-astro: 0.14.1
