packages:
 - 'packages/*'
 - 'docs'

catalogs:
 tooling:
  'typescript': '5.8.2'
  'esbuild': '0.25.0'
  '@babel/parser': 7.26.9
  'rimraf': '6.0.1'
  'commander': '13.1.0'
  'ora': '8.2.0'
  'recast': '^0.23.4' # to remove ?
  '@types/node': '22.13.9'

 vite:
  'vite': '6.2.1'

 testing:
  # unit
  'vitest': '3.0.4'
  '@vitest/coverage-v8': '3.0.4'
  '@testing-library/jest-dom': '6.6.3'
  '@testing-library/svelte': '5.2.4'
  'jsdom': '26.0.0'
  # e2e
  '@playwright/test': '1.51.0'

 linting:
  '@eslint/compat': '1.2.7'
  '@eslint/js': '9.22.0'
  '@theguild/prettier-config': '3.0.0'
  '@types/eslint': '9.6.1'
  '@typescript-eslint/parser': '8.26.0'
  'eslint': '9.22.0'
  'eslint-plugin-pnpm-catalogs': '0.1.0'
  'eslint-plugin-svelte': '3.1.0'
  'eslint-plugin-unused-imports': '4.1.4'
  'globals': '16.0.0'
  'prettier': '3.5.3'
  'prettier-plugin-svelte': '3.3.2'
  'prettier-plugin-tailwindcss': '0.6.6'
  'typescript-eslint': '8.26.0'
  jsonc-eslint-parser: 2.4.0

 lib-author-helper:
  '@changesets/changelog-github': '0.5.1'
  '@changesets/cli': '2.28.1'
  'publint': '0.3.1'
  'tslib': '2.8.0'
  'rollup-plugin-visualizer': '5.14.0'

 lib-dep-publish:
  'esm-env': '^1.2.2'
  '@types/vary': '1.1.3'
  'vary': '^1.1.2'
  '@types/micromatch': '4.0.9'
  'micromatch': '4.0.8'

 sveltekit:
  '@sveltejs/kit': '2.19.0'
  '@sveltejs/package': '2.3.7'
  '@sveltejs/vite-plugin-svelte': '5.0.1'
  '@sveltejs/adapter-auto': '4.0.0'
  '@sveltejs/adapter-node': '5.2.12'
  '@sveltejs/adapter-static': '3.0.4'

 svelte:
  'svelte': '5.23.0'
  'svelte-check': '4.1.1'

 svelte-dep:
  '@sveltejs/kit': '^2.16.0'
  'svelte': '^5.0.0'

 remult:
  'remult': '2.7.31'

 docs:
  '@astrojs/starlight': 0.32.2
  accessible-astro-components: 4.1.0
  astro: 5.4.2
  astro-icon: 1.1.5
  sharp: 0.33.5
  prettier-plugin-astro: 0.14.1
