onlyBuiltDependencies:
 - esbuild

patchedDependencies:
 '@sveltejs/package': patches/@sveltejs__package.patch

packages:
 - 'packages/*'
 - 'docs'

catalogs:
 tooling:
  'typescript': '5.9.2'
  'esbuild': '0.25.0'
  '@babel/parser': 7.27.0
  '@babel/types': 7.27.0
  'rimraf': '6.0.1'
  'commander': '14.0.0'
  'ora': '9.0.0'
  'recast': '^0.23.4'
  'tsx': '4.20.3'

 vite:
  'vite': '^7.0.0'

 testing:
  # unit
  'vitest': '3.2.4'
  '@vitest/ui': 3.2.4
  '@vitest/coverage-v8': '3.2.4'
  '@testing-library/jest-dom': '6.9.1'
  '@testing-library/svelte': '5.2.4'
  'jsdom': '26.1.0'
  # e2e
  '@playwright/test': '1.56.0'

 linting:
  '@eslint/compat': '1.4.0'
  '@eslint/js': '9.37.0'
  '@theguild/prettier-config': '3.0.0'
  '@types/eslint': '9.6.1'
  '@typescript-eslint/parser': '8.46.1'
  'eslint': '9.37.0'
  'eslint-config-prettier': '10.1.5'
  'eslint-plugin-pnpm': '1.1.0'
  'eslint-plugin-svelte': '3.11.0'
  'eslint-plugin-unused-imports': '4.1.4'
  'globals': '16.3.0'
  'prettier': '^3.6.1'
  'prettier-plugin-svelte': '3.4.0'
  'prettier-plugin-tailwindcss': '0.6.14'
  'typescript-eslint': '8.46.1'
  jsonc-eslint-parser: 2.4.0
  yaml-eslint-parser: 1.3.0

 linting-oxc:
  oxlint: 1.23.0
  oxlint-tsgolint: 0.2.0
  eslint-plugin-oxlint: 1.23.0

 lib-author-helper:
  '@changesets/changelog-github': '0.5.1'
  '@changesets/cli': '2.29.7'
  'publint': '0.3.1'
  'tslib': '2.8.0'
  'rollup-plugin-visualizer': '6.0.1'

 lib-dep-publish:
  'esm-env': '^1.2.2'
  '@types/vary': '1.1.3'
  'vary': '^1.1.2'
  '@types/micromatch': '4.0.9'
  'micromatch': '4.0.8'

 sveltekit:
  '@sveltejs/kit': '2.46.5'
  '@sveltejs/package': '2.4.0'
  '@sveltejs/vite-plugin-svelte': '6.1.0'
  '@sveltejs/adapter-auto': '6.1.1'
  '@sveltejs/adapter-node': '5.2.12'

 svelte:
  'svelte': '5.40.0'
  'svelte-check': '4.3.0'

 svelte-dep:
  '@sveltejs/kit': '^2.16.0'
  'svelte': '^5.0.0'

 remult:
  'remult': '3.2.2'

 docs:
  '@astrojs/starlight': 0.36.0
  accessible-astro-components: 4.1.0
  astro: 5.12.3
  astro-icon: 1.1.5
  sharp: 0.34.1
  prettier-plugin-astro: 0.14.1
 conflicts_linting-oxc_h0_2_0:
  oxlint-tsgolint: ^0.2.0
 conflicts_eslint-plugin-oxlint_h:
  eslint-plugin-oxlint: ^
 conflicts_eslint-plugin-oxlint_:
  eslint-plugin-oxlint: ''
catalog:
 eslint-plugin-oxlint: ^1.23.0
 oxlint: ^1.23.0
 oxlint-tsgolint: ^0.2.0
