# Typical File for extension: vscode-graphql & CodeGen!
projects:
  default:
    schema:
      - ./src/lib/modules/**/typedefs/*.graphql
      - ./$houdini/graphql/schema.graphql
    documents:
      - ./src/lib/modules/**/graphql/*.gql
      - ./$houdini/graphql/documents.gql
    extensions:
      codegen:
        generates:
          ./src/lib/graphql/$kitql/graphqlTypes.ts:
            plugins:
              - typescript

          ./src/lib/modules/:
            preset: graphql-modules
            presetConfig:
              baseTypesPath: ../graphql/$kitql/graphqlTypes.ts
              importBaseTypesFrom: $graphql/$kitql/graphqlTypes
              filename: $kitql/moduleTypes.ts
            plugins:
              - typescript
              - typescript-resolvers
            config:
              contextType: $graphql/kitQLServer#IKitQLContext
              scalars:
                Date: ../helpers/scalarTypes#CodegenDate
                DateTime: Date

        config:
          useTypeImports: true
