configs:
  modulesFolder: ./src/lib/modules
  moduleOutputFolder: _kitql
  outputFolder: ./src/lib/graphql/_kitql

actions:
  # - createBaseStructure: true
  # createEnumsModule:
  # prismaFile: ./prisma/schema.prisma
  # importBaseTypesFrom: $graphql/_kitql/graphqlTypes

  mergeModuleTypedefs: true
  mergeModuleResolvers: true
  mergeContexts: true
  mergeModules: true
