/** 
 * This file was generated by 'vite-plugin-kit-routes'
 * 
 *      >> DO NOT EDIT THIS FILE MANUALLY <<
 */

/**
 * PAGES
 */
export const PAGES = {
  "_ROOT": `/`,
  "subGroup": `/subGroup`,
  "subGroup2": `/subGroup2`,
  "contract": (params?: { lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/contract`
  },
  "contract_id": (params: { id: (string | number), lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/contract/${params.id}`
  },
  "gp_one": (params?: { lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/gp/one`
  },
  "gp_two": (params?: { lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/gp/two`
  },
  "main": (params?: { lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/main`
  },
  "match_id_int": (params: { id: (string | number), lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/match/${params.id}`
  },
  "site": (params?: { lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/site`
  },
  "site_id": (params: { id: (string | number), lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/site/${params.id}`
  },
  "site_contract_siteId_contractId": (params: { siteId: (string | number), contractId: (string | number), lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/site_contract/${params.siteId}-${params.contractId}`
  },
  "a_rest_z": (params: { rest: (string | number)[] }) => {
    return `/a/${params.rest?.join('/')}/z`
  },
  "lay_normal": `/lay/normal`,
  "lay_root_layout": `/lay/root-layout`,
  "lay_skip": `/lay/skip`
}

/**
 * SERVERS
 */
export const SERVERS = {
  "GET_contract": (params?: { lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/contract`
  },
  "POST_contract": (params?: { lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/contract`
  },
  "GET_site": (params?: { lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/site`
  },
  "GET_api_graphql": `/api/graphql`,
  "POST_api_graphql": `/api/graphql`
}

/**
 * ACTIONS
 */
export const ACTIONS = {
  "default_contract_id": (params: { id: (string | number), lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/contract/${params.id}`
  },
  "create_site": (params?: { lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/site?/create`
  },
  "update_site_id": (params: { id: (string | number), lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/site/${params.id}?/update`
  },
  "delete_site_id": (params: { id: (string | number), lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/site/${params.id}?/delete`
  },
  "noSatisfies_site_contract": (params?: { lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/site_contract?/noSatisfies`
  },
  "send_site_contract_siteId_contractId": (params: { siteId: (string | number), contractId: (string | number), lang?: (string | number) }) => {
    return `${params?.lang ? `/${params?.lang}`: ''}/site_contract/${params.siteId}-${params.contractId}?/send`
  }
}

/**
 * LINKS
 */
export const LINKS = {
  
}

/**
 * Append search params to a string
 */
const appendSp = (sp?: Record<string, string | number | undefined>, prefix: '?' | '&' = '?') => {
  if (sp === undefined) return ''
  const mapping = Object.entries(sp)
    .filter(c => c[1] !== undefined)
    .map(c => [c[0], String(c[1])])

  const formated = new URLSearchParams(mapping).toString()
  if (formated) {
    return `${prefix}${formated}`
  }
  return ''
}

/**
* Add this type as a generic of the vite plugin `kitRoutes<KIT_ROUTES>`.
* 
* Full example:
* ```ts
* import type { KIT_ROUTES } from '$lib/ROUTES'
* import { kitRoutes } from 'vite-plugin-kit-routes'
* 
* kitRoutes<KIT_ROUTES>({
*  PAGES: {
*    // here, key of object will be typed!
*  }
* })
* ```
*/
export type KIT_ROUTES = { 
  PAGES: { '_ROOT': never, 'subGroup': never, 'subGroup2': never, 'contract': 'lang', 'contract_id': 'id' | 'lang', 'gp_one': 'lang', 'gp_two': 'lang', 'main': 'lang', 'match_id_int': 'id' | 'lang', 'site': 'lang', 'site_id': 'id' | 'lang', 'site_contract_siteId_contractId': 'siteId' | 'contractId' | 'lang', 'a_rest_z': 'rest', 'lay_normal': never, 'lay_root_layout': never, 'lay_skip': never }
  SERVERS: { 'GET_contract': 'lang', 'POST_contract': 'lang', 'GET_site': 'lang', 'GET_api_graphql': never, 'POST_api_graphql': never }
  ACTIONS: { 'default_contract_id': 'id' | 'lang', 'create_site': 'lang', 'update_site_id': 'id' | 'lang', 'delete_site_id': 'id' | 'lang', 'noSatisfies_site_contract': 'lang', 'send_site_contract_siteId_contractId': 'siteId' | 'contractId' | 'lang' }
  LINKS: Record<string, never>
  Params: { lang: never, id: never, siteId: never, contractId: never, rest: never }
}
