mutation AddStar($id: ID!) {
	addStar(input: { starrableId: $id, clientMutationId: "From KitQL" }) {
		clientMutationId
		starrable {
			__typename
			id
			stargazers {
				totalCount
			}
			viewerHasStarred
		}
	}
}
