mutation RemoveStar($id: ID!) {
	removeStar(input: { starrableId: $id, clientMutationId: "From KitQL" }) {
		clientMutationId
		starrable {
			id
			stargazers {
				totalCount
			}
			viewerHasStarred
		}
	}
}
