---
projects:
  default:
    schema:
      - src/lib/modules/**/typedefs/*.graphql
      # - $houdini/graphql/schema.graphql
    documents:
      - src/lib/modules/**/graphql/*.gql
      # - $houdini/graphql/documents.gql
    extensions:
      codegen:
        generates:
          src/lib/modules:
            preset: graphql-modules
            presetConfig:
              baseTypesPath: '../graphql/$kitql/graphqlTypes.ts'
              importBaseTypesFrom: '$graphql/$kitql/graphqlTypes'
              filename: $kitql/moduleTypes.ts
            plugins:
              - typescript
              - typescript-resolvers
            config:
              contextType: '$graphql/kitQLServer#IKitQLContext'
              useTypeImports: true
              # scalars:
              #   - Date: "../helpers/scalarTypes#CodegenDate"
              #     DateTime: Date
              #     PrismaDecimal: "../helpers/scalarTypes#CodegenDecimal"
        config:
          useTypeImports: true
