query Issues(
	$repository: String!
	$owner: String!
	$filters: IssueFilters
	$take: Int = 25
	$cursor: String
) {
	repository(name: $repository, owner: $owner) {
		issues(last: $take, after: $cursor, filterBy: $filters) {
			pageInfo {
				endCursor
			}
			nodes {
				...issuePreview
			}
		}
	}
}
