schema: ./src/lib/graphql/schema.graphql

documents: ./src/lib/graphql/operations/**/*.gql

generates:
  ./src/lib/graphql/generated/types.ts:
    preset: graphql-modules
    presetConfig:
      baseTypesPath: .
      importBaseTypesFrom: $lib/graphql/generated/types
      filename: kitql/moduleTypes.ts
    plugins:
      - typescript
      - typescript-resolvers
      - typescript-operations
      - typed-document-node
    # config:
    #   contextType: '$lib/graphql/yogaApp#IYogaContext'

  ./src/lib/kitql/generated/stores.ts:
    plugins:
      - '@kitql/graphql-codegen'
    config:
      importBaseTypesFrom: $lib/graphql/generated/types

config:
  useTypeImports: true
